#/bin/bash

if ! [ -f out/template.fls ]; then
    echo "Cannot find file 'out/template.fls', which is generated by latexmk"
    echo "Please use 'latexmk' command to compile template first, then run"
    echo "this script under the project root dir to count words"
    exit 1
fi

cat out/template.fls                 \
    | uniq                            \
    | grep body                       \
    | grep .tex                       \
    | grep -v thanksto.tex            \
    | grep -v acknowledgement.tex     \
    | grep -v review.tex              \
    | grep -v original.tex            \
    | grep -v cv.tex                  \
    | cut -d ' ' -f 2                 \
    | awk '{ print "\\input{"$1"}" }' \
    > out/template.wordcnt           \
;

texcount out/template.wordcnt -inc
